const { H1, H2, H3, P, BUL, TAB, EQ } = require("../lib");

module.exports = [
  H1(3, "REQUIREMENT SPECIFICATION"),

  H2("3.1", "Introduction"),
  P("A requirement specification describes *what* the system must do and *under which constraints*, before the design describes *how*. For PixelProse the requirements were derived from the objectives in Section 1.3, the research gaps in Section 2.2 and the practical context of the project: it must run on the laptops students already own, it must work without paid services, and it must be demonstrable live in a classroom. This chapter lists the hardware and software requirements, the functional and non-functional requirements, the feasibility study and the cost estimation."),

  H2("3.2", "Hardware Requirements"),
  P("Deep-learning inference is dominated by matrix multiplications, so processor speed and memory determine the user experience. PixelProse loads four BLIP networks totalling about 1.25 billion parameters. In 32-bit floating point this needs roughly 5 GB of RAM, which drives the memory requirement in {tab:hw}. A GPU is optional: on CPU a caption takes about four seconds, while a CUDA GPU brings it well under one second."),
  TAB("hw",
    ["Component", "Minimum", "Recommended"],
    [
      ["Processor", "4-core x86-64 or Apple Silicon CPU (2015 or newer)", "6–8 core CPU (Intel Core i5/i7 10th gen+, AMD Ryzen 5/7, Apple M1+)"],
      ["Memory (RAM)", "8 GB (with VQA disabled or base model)", "16 GB"],
      ["Storage", "6 GB free (models ≈ 4 GB + environment)", "10 GB free SSD"],
      ["GPU", "Not required", "NVIDIA GPU with ≥ 4 GB VRAM (CUDA) or Apple M-series (MPS)"],
      ["Display", "1366 × 768", "1920 × 1080 or projector"],
      ["Camera (optional)", "Any webcam for live capture", "HD webcam"],
      ["Network", "Internet for the one-time model download (≈ 4 GB)", "Wi-Fi for LAN demos on phones"],
    ],
    "Hardware requirements",
    [1.5, 2.9, 3.4]),

  H2("3.3", "Software Requirements"),
  TAB("sw",
    ["Category", "Software / Library", "Version", "Purpose"],
    [
      ["Operating system", "Windows 10/11, macOS 12+, Ubuntu 20.04+", "—", "Host platform"],
      ["Language", "Python", "3.10 – 3.12", "Backend, AI pipeline, scripts"],
      ["Deep learning", "PyTorch", "≥ 2.2", "Tensor computation, autograd for Grad-CAM"],
      ["Models", "Hugging Face Transformers", "4.56 – 4.x", "BLIP models, tokenizers, generation"],
      ["Model hub", "huggingface_hub, safetensors", "≥ 0.23, ≥ 0.4", "Downloading and loading weights"],
      ["Web framework", "FastAPI + Uvicorn", "≥ 0.110, ≥ 0.27", "REST API, OpenAPI docs, ASGI server"],
      ["Uploads", "python-multipart", "≥ 0.0.9", "Multipart form parsing"],
      ["Imaging", "Pillow, NumPy", "≥ 10.0, ≥ 1.26", "Decoding, EXIF, palette, metadata"],
      ["Frontend", "HTML5, CSS3, JavaScript (ES2020 modules)", "—", "User interface, Canvas, Web Speech API"],
      ["Browser", "Chrome, Edge, Firefox or Safari", "Latest", "Running the web interface"],
      ["Testing", "pytest, httpx", "≥ 8.0, ≥ 0.27", "Automated unit and API tests"],
      ["Tools", "Git/GitHub, VS Code, PlantUML, Matplotlib", "—", "Version control, editing, diagrams and charts"],
    ],
    "Software requirements",
    [1.4, 2.6, 1.3, 2.5]),

  H2("3.4", "Feasibility Study"),
  H3("3.4.1", "Technical Feasibility"),
  P("All required components are mature and open source. BLIP models are publicly available through the Hugging Face Hub under the BSD-3-Clause licence, and PyTorch runs them efficiently on CPUs. Our measurements (Chapter 7) show a caption in about 3.9 seconds on a 4-core CPU with the default configuration, which is acceptable for interactive use. The team had prior experience with Python and web development, and the attention mechanism and transformers are covered in the Advanced AI syllabus. The project is therefore technically feasible."),
  H3("3.4.2", "Economic Feasibility"),
  P("The project uses only free and open-source software and runs on the students' existing laptops. No GPU purchase, cloud computing credits or paid API subscriptions are required. The only recurring cost is electricity during development, which is negligible. Compared with commercial captioning APIs that charge per image, PixelProse has zero marginal cost per caption. The project is economically feasible."),
  H3("3.4.3", "Operational Feasibility"),
  P("The system is operated through a web browser with a familiar drag-and-drop interface. One-click setup and start scripts for Windows (setup.bat, start.bat) and macOS/Linux (setup.sh, start.sh) remove the need for command-line knowledge. The interface provides immediate visual feedback, tooltips and keyboard shortcuts, so users need no training. The project is operationally feasible."),
  H3("3.4.4", "Schedule Feasibility"),
  P("Using pre-trained models avoids the months of training that building a model from scratch would take. The work was divided into literature study, backend pipeline, interface, evaluation, and documentation and presentation, which were executed partly in parallel by the three team members within the semester. The project is feasible within the academic schedule."),
  H3("3.4.5", "Legal and Ethical Feasibility"),
  P("The BLIP weights are released under the BSD-3-Clause licence, which permits academic and commercial use with attribution. The test images come from public test-image collections of open-source projects and are used only for evaluation. Because images never leave the user's machine, the system avoids the privacy concerns of cloud APIs. We acknowledge that models trained on web data can reflect social biases; this is discussed as a limitation and future work."),

  H2("3.5", "Cost Estimation"),
  P("We estimate the development effort with the **Basic COCOMO** model {ref:cocomo} in *organic* mode, which suits small teams working on familiar problems. The implemented system contains about 4.6 thousand non-blank lines of code: 1,493 lines of Python (application and scripts), 180 lines of tests, 1,775 lines of JavaScript, 625 lines of CSS and 562 lines of HTML. With KLOC = 4.6:"),
  EQ("cocomo_e", "E = a · (KLOC)^b = 2.4 × (4.6)^1.05 ≈ 12.0 person-months"),
  EQ("cocomo_d", "D = c · (E)^d = 2.5 × (12.0)^0.38 ≈ 6.4 months"),
  EQ("cocomo_p", "P = E / D = 12.0 / 6.4 ≈ 1.9 persons"),
  P("The model therefore predicts about two people working for six to seven months, which is consistent with our three-member team working part-time alongside coursework during the semester. {tab:cost} converts the effort into a notional monetary cost, assuming an intern-level rate of ₹25,000 per person-month."),
  TAB("cost",
    ["Item", "Basis", "Cost (₹)"],
    [
      ["Development effort", "12.0 person-months × ₹25,000", "3,00,000"],
      ["Hardware", "Existing student laptops (no purchase)", "0"],
      ["Software and libraries", "Open source (PyTorch, Transformers, FastAPI, …)", "0"],
      ["Pre-trained models", "Salesforce BLIP, BSD-3-Clause", "0"],
      ["Cloud / API usage", "Not required (runs locally)", "0"],
      ["Internet (model download)", "≈ 4 GB one-time on existing connection", "≈ 50"],
      ["Printing and binding of report", "Estimated", "≈ 1,500"],
      ["Total (notional)", "", "≈ 3,01,550"],
    ],
    "Cost estimation",
    [2.4, 3.8, 1.6]),
  P("The actual cash expenditure is only the printing cost; the development-effort figure represents the value of the work produced."),
  H2("3.6", "Functional Requirements"),
  P("Functional requirements specify the behaviour the system must provide. They are listed in {tab:fr} with an identifier used for traceability to the test cases in Chapter 6."),
  TAB("fr",
    ["ID", "Requirement"],
    [
      ["FR-1", "The system shall accept an image by file upload, drag-and-drop, clipboard paste, public URL, webcam capture or selection from bundled samples."],
      ["FR-2", "The system shall validate the image (format, size ≤ 15 MB, decodability) and reject invalid input with a clear message."],
      ["FR-3", "The system shall generate an English caption for the image using a pre-trained BLIP model."],
      ["FR-4", "The system shall generate multiple candidate captions and display them with their scores."],
      ["FR-5", "The system shall compute a confidence score for every caption and a probability for every word."],
      ["FR-6", "The system shall re-rank candidates using an image–text matching model and display the match probability."],
      ["FR-7", "The system shall display a word-level attention heatmap over the image for any word of the caption."],
      ["FR-8", "The system shall answer free-form questions about the image (visual question answering)."],
      ["FR-9", "The system shall score user-written descriptions against the image."],
      ["FR-10", "The system shall let the user choose the model (large/base), caption style, candidate count, length, beam width, creativity and a guided prefix."],
      ["FR-11", "The system shall provide keywords, hashtags, a colour palette, image metadata, stage timings and accessible alt-text HTML."],
      ["FR-12", "The system shall read captions aloud and export a shareable caption card."],
      ["FR-13", "The system shall caption up to 12 images in batch mode and export the results as CSV or JSON."],
      ["FR-14", "The system shall store the last 30 results in the browser history and allow them to be restored."],
      ["FR-15", "The system shall expose all features through a documented REST API and a command-line interface."],
    ],
    "Functional requirements",
    [0.8, 7.0]),

  H2("3.7", "Non-Functional Requirements"),
  BUL([
    "**Performance:** a caption with the default settings shall be produced in under 5 seconds on a 4-core laptop CPU and under 1 second on a GPU. Repeated requests for the same image and settings shall be served from cache almost instantly.",
    "**Accuracy:** the default configuration shall achieve a CIDEr-D above 1.9 and an image–text match above 90 % on the bundled evaluation set (Chapter 7).",
    "**Usability:** a first-time user shall be able to caption an image in under 30 seconds without instructions. The interface shall work on screens from 390 px (phone) to 1920 px wide.",
    "**Accessibility:** keyboard navigation, visible focus states, ARIA labels, reduced-motion support and text-to-speech shall be provided in line with WCAG 2.1 {ref:wcag}.",
    "**Reliability:** a failure in one optional model (ITM or VQA) shall not stop captioning; errors shall be reported as readable messages.",
    "**Security and privacy:** images shall be processed locally. URL fetching shall block private network addresses (SSRF protection), uploads shall be size-limited and all user text shall be escaped before rendering.",
    "**Portability:** the system shall run on Windows, macOS and Linux with CPU, CUDA or Apple MPS acceleration, selected automatically.",
    "**Maintainability:** the code shall be modular (separate services for captioning, matching, VQA and image handling), documented and covered by automated tests.",
  ]),

];
