const { H1, H2, H3, P, BUL, NUM, FIG, TAB, EQ, CODE } = require("../lib");

module.exports = [
  H1(5, "METHODOLOGY"),

  H2("5.1", "Introduction"),
  P("This chapter explains how PixelProse converts pixels into prose. We first present the overall system block diagram and then describe each stage: image pre-processing, the Vision Transformer encoder, the image-grounded text decoder, BLIP pre-training, the decoding algorithms, candidate scoring and re-ranking, Grad-CAM explainability, visual question answering, post-processing and the evaluation metrics. Wherever possible the mathematical formulation is given, followed by the concrete parameter values used in our implementation."),

  H2("5.2", "System Block Diagram"),
  P("{fig:block} shows the processing pipeline. An input image is pre-processed and encoded once by the Vision Transformer into 577 embedding vectors. The text decoder, conditioned on these embeddings through cross-attention, generates several candidate captions with beam search (and optionally nucleus sampling). Each candidate is scored by its token probabilities, and the Image–Text Matching (ITM) model independently checks how well it fits the image. The two scores are blended to select the best caption, which is post-processed into a sentence, keywords, hashtags and alt-text. Two side branches reuse the pipeline: Grad-CAM explains the chosen caption word by word, and BLIP-VQA answers user questions."),
  FIG("block", "block_diagram.png", "System block diagram of PixelProse", 3.3),

  H2("5.3", "Image Pre-processing"),
  P("Uploaded images arrive in many formats, orientations and sizes. The pre-processing stage makes them uniform:"),
  NUM([
    "**Validation:** the file must be at most 15 MB, decode successfully with Pillow and be one of JPEG, PNG, WEBP, GIF, BMP or TIFF. A decompression-bomb guard rejects images above 80 megapixels.",
    "**Orientation:** the EXIF orientation tag is applied so that photographs taken in portrait mode are upright.",
    "**Colour:** images are converted to 3-channel RGB. Transparent PNGs are composited onto white, because otherwise transparent pixels would become black.",
    "**Working size:** images larger than 1600 px are down-scaled with Lanczos filtering to save memory, since the models see only 384×384 pixels.",
    "**Model input:** the BLIP processor resizes the image to 384×384 with bicubic interpolation, scales pixel values to [0, 1] and normalises each channel with the statistics used during pre-training ({eq:norm}).",
  ]),
  EQ("norm", "x̂_c = (x_c / 255 − μ_c) / σ_c,   μ = (0.4815, 0.4578, 0.4082),   σ = (0.2686, 0.2613, 0.2758)"),

  H2("5.4", "Vision Transformer Encoder"),
  P("The image encoder is a Vision Transformer {ref:dosovitskiy}, ViT-L/16 in BLIP-large. As illustrated in {fig:patch}, the 384×384 image is split into non-overlapping 16×16 patches, giving N = (384/16)² = 576 patches. Each patch x_p ∈ ℝ^(16·16·3) is flattened and linearly projected to a D-dimensional embedding (D = 1024). A learnable [CLS] token is prepended, and learnable position embeddings E_pos are added so that the model knows where each patch came from:"),
  FIG("patch", "patch_grid.png", "The image is resized to 384×384 and split into 24×24 = 576 patches of 16×16 pixels", 5.6),
  EQ("patch", "z₀ = [ x_cls ; x_p¹E ; x_p²E ; … ; x_p⁵⁷⁶E ] + E_pos,    E ∈ ℝ^(768 × 1024),  E_pos ∈ ℝ^(577 × 1024)"),
  P("The sequence then passes through L = 24 transformer layers. Each layer applies multi-head self-attention (MHSA) and a feed-forward network (MLP), both with pre-layer-normalisation and residual connections:"),
  EQ("block1", "z′_ℓ = MHSA( LN(z_ℓ₋₁) ) + z_ℓ₋₁"),
  EQ("block2", "z_ℓ = MLP( LN(z′_ℓ) ) + z′_ℓ ,    ℓ = 1 … L"),
  P("Self-attention {ref:vaswani} lets every patch gather information from every other patch. For queries Q, keys K and values V obtained by linear projections of the input:"),
  EQ("attn", "Attention(Q, K, V) = softmax( Q Kᵀ / √d_k ) V"),
  EQ("mhsa", "MHSA(X) = Concat(head₁, …, head_h) W^O ,   head_i = Attention(X W_i^Q , X W_i^K , X W_i^V)"),
  P("ViT-L/16 uses h = 16 heads of dimension d_k = 64. The output is a matrix of 577 × 1024 *image embeddings*, a contextualised description of every patch plus a global [CLS] summary, which all subsequent stages consume. In PixelProse this encoding is computed **only once per image** and reused for every candidate caption."),

  H2("5.5", "Image-Grounded Text Decoder"),
  P("The caption is produced by a 12-layer BERT-style {ref:bert} transformer decoder ({fig:blip}). Each decoder layer has three sub-layers: *causal* self-attention over the words generated so far (masked so that position t cannot see positions after t), **cross-attention** from the words to the image embeddings, and a feed-forward network. Cross-attention is where vision meets language. The queries come from the text hidden states H and the keys and values come from the image embeddings V:"),
  EQ("cross", "CrossAttn(H, V) = softmax( (H W^Q)(V W^K)ᵀ / √d_k ) (V W^V)"),
  P("A language-modelling head maps the final hidden state to a probability distribution over the 30,524-token WordPiece vocabulary. The probability of a whole caption factorises by the chain rule:"),
  EQ("chain", "P(w₁ … wₙ | I) = ∏ₜ P( wₜ | w₁ … wₜ₋₁ , I )"),
  FIG("blip", "blip_architecture.png", "Architecture of the BLIP captioning model (ViT encoder and image-grounded decoder)", 4.6),
  P("The BLIP captioner was fine-tuned with the textual prompt “a picture of”. PixelProse therefore always starts decoding from the token sequence [DEC] a picture of and strips this prefix from the output. Decoding without it causes BLIP-large to emit nonsense tokens such as “arafed” learned from noisy web alt-text. When the user supplies a *guided prefix* (for example “a painting of”), that prefix replaces the default prompt and is kept in the caption. This is known as conditional captioning."),

  H2("5.6", "BLIP Pre-training Objectives"),
  P("BLIP {ref:blip} is pre-trained jointly with three objectives that share the image encoder. Understanding them explains why PixelProse can verify and explain captions without any additional training:"),
  BUL([
    "**Image–Text Contrastive loss (ITC)** aligns the unimodal image and text embeddings. With similarity s(I, T) = g_v(v_cls)ᵀ g_t(t_cls) between projected [CLS] features and a temperature τ, the model maximises the softmax probability of the matching pair within a batch ({eq:itc}).",
    "**Image–Text Matching loss (ITM)** trains a binary classifier on the multimodal [CLS] output of a text encoder that cross-attends to the image, predicting whether an image–text pair matches. Hard negatives are mined using the contrastive similarity ({eq:itm}).",
    "**Language Modelling loss (LM)** trains the image-grounded decoder to generate the caption autoregressively ({eq:lm}).",
  ]),
  EQ("itc", "p_i2t(I) = exp( s(I, T) / τ ) / Σₘ exp( s(I, Tₘ) / τ ) ,   L_itc = ½ E[ H(y_i2t, p_i2t) + H(y_t2i, p_t2i) ]"),
  EQ("itm", "L_itm = E_(I,T) [ H( y_itm , p_itm(I, T) ) ]"),
  EQ("lm", "L_lm = − Σₜ log P_θ( wₜ | w<ₜ , I )"),
  P("In addition, BLIP's **CapFilt** bootstrapping step uses a fine-tuned captioner to write synthetic captions for 129 million web images and a fine-tuned ITM filter to remove noisy captions, which is why the model generalises well to everyday photographs. PixelProse uses the LM-trained decoder to *generate*, the ITM head to *verify* and *explain*, and the ITC projections to report a fast similarity score."),

  H2("5.7", "Decoding Strategies"),
  P("Generating a caption means searching for a high-probability word sequence. Exhaustive search is impossible because the number of sequences grows as |V|ⁿ. PixelProse implements three strategies, exposed to users as caption styles."),
  H3("5.7.1", "Greedy Decoding (baseline)"),
  P("Greedy decoding picks the single most probable word at each step, wₜ = argmax_w P(w | w<ₜ, I). It is fast but short-sighted: an early locally-best word can lead to a poor sentence. It is used only as the baseline in our evaluation."),
  H3("5.7.2", "Beam Search (Balanced mode)"),
  P("Beam search keeps the k most probable partial sentences (the *beam*) at each step, as illustrated in {fig:beam}. Candidates are ranked by their length-normalised log-probability:"),
  EQ("beam", "score(y) = ( 1 / |y|^α ) · Σₜ log P( yₜ | y<ₜ , I ) ,   α = 1"),
  FIG("beam", "beam_search.png", "Beam search keeps the k best partial captions at every step (pruned paths shown dashed)", 5.8),
  P("**Algorithm – Beam search with candidates:**"),
  NUM([
    "Initialise the beam with the prompt sequence [DEC] a picture of and score 0.",
    "For each step t = 1 … max_new_tokens (30): expand every hypothesis in the beam with every vocabulary token and compute the new cumulative log-probability.",
    "Apply the repetition penalty ({eq:rep}) and block any token that would repeat an already generated 3-gram.",
    "Keep the k = 5 highest-scoring hypotheses; move hypotheses that produced the end token [SEP] (after at least 5 new tokens) to the finished list.",
    "Stop when k hypotheses are finished and no open hypothesis can beat them (early stopping).",
    "Return the top num_candidates finished hypotheses as candidate captions.",
  ]),
  EQ("rep", "z_w ← z_w / θ if z_w > 0,  else z_w · θ ,   for every previously generated token w,   θ = 1.1"),
  H3("5.7.3", "Nucleus (Top-p) Sampling (Detailed and Creative modes)"),
  P("Beam search tends to produce safe but generic sentences {ref:holtzman}. Nucleus sampling instead samples each word from the smallest set of words V⁽ᵖ⁾ whose cumulative probability exceeds p, after sharpening or flattening the distribution with a temperature T:"),
  EQ("temp", "P_T(w) = exp( z_w / T ) / Σ_v exp( z_v / T )"),
  EQ("topp", "V⁽ᵖ⁾ = smallest set with Σ_(w ∈ V⁽ᵖ⁾) P_T(w) ≥ p ,   P′(w) = P_T(w) / Σ_(v ∈ V⁽ᵖ⁾) P_T(v)  for w ∈ V⁽ᵖ⁾, else 0"),
  P("PixelProse uses p = 0.9 and a default temperature T = 0.9 (adjustable from 0.3 to 1.5 through the *Creativity* slider). The *Detailed* mode merges ⌈n/2⌉+1 beam candidates with ⌈n/2⌉+1 sampled candidates, and the *Creative* mode uses sampling only."),

  H2("5.8", "Candidate Scoring and Re-ranking"),
  H3("5.8.1", "Language-Model Confidence"),
  P("After decoding, duplicate candidates (after cleaning) are removed and all remaining candidates are scored in **one batched teacher-forced forward pass** of the decoder over the shared image embeddings. For a candidate with generated tokens w₁ … wₙ (including the end token), its confidence is the geometric mean of the token probabilities, which equals the inverse of its perplexity:"),
  EQ("conf", "conf = exp( (1/n) Σₜ log P( wₜ | w<ₜ , I ) ) = 1 / PPL"),
  P("WordPiece tokens are merged into words for display (for example sky + ##scraper → skyscraper), and a word's probability is the product of its pieces' probabilities. These per-word probabilities are drawn as the *word-by-word confidence* bar chart in the interface."),
  H3("5.8.2", "Image–Text Matching Verification"),
  P("Language-model confidence measures fluency, not truthfulness: a fluent sentence may mention an object that is not in the picture. PixelProse therefore re-reads each candidate with the separately fine-tuned **BLIP-ITM** model. The candidate text is encoded by a BERT encoder that cross-attends to the image, and the ITM head outputs the probability that the pair matches:"),
  EQ("pitm", "P_itm(I, T) = softmax( W_itm · h_cls(I, T) )₁"),
  P("The final score blends grounding and fluency, and the highest-scoring candidate becomes the caption:"),
  EQ("final", "S(T) = 0.65 · P_itm(I, T) + 0.35 · conf(T)"),
  P("The weights favour grounding while still penalising ungrammatical candidates. The contrastive cosine similarity cos(g_v(v_cls), g_t(t_cls)) from the ITC projections is also reported. It is cheaper but less discriminative than ITM, and it powers the *similarity* value in the Match tab."),

  H2("5.9", "Explainability with Grad-CAM"),
  P("To show *where* the model looked for each word, we apply Grad-CAM {ref:gradcam} to the cross-attention of the ITM model, following the grounding approach of ALBEF and BLIP {ref:albef} ({fig:gradcam}). Let A ∈ ℝ^(H×T×577) be the cross-attention probabilities of layer 8 (H = 12 heads, T text tokens, 1 + 576 image tokens) and s the ITM *match* logit. We back-propagate s to the attention map and weight the attention by the positive part of its gradient:"),
  EQ("grad", "G = ∂s / ∂A"),
  EQ("cam", "CAM_t = (1/H) Σ_h A_(h,t,1:) ⊙ max( 0 , G_(h,t,1:) )  ∈ ℝ^(24 × 24)"),
  P("The positive gradient keeps only the attention that *increased* the match score, which makes the maps word-specific rather than generic saliency. Raw maps are peaky, often only two or three patches, so each map is smoothed with a 5×5 Gaussian kernel (σ = 1 patch), min–max normalised and gamma-corrected ({eq:gamma}) to reveal weaker but relevant regions. Word pieces are averaged into words, stop-words are flagged, and an overall map is computed as the mean over content words. The browser colours the 24×24 grid with a turbo colour map, upsamples it with smoothing, and blends it over the photograph at a user-selected opacity."),
  EQ("gamma", "M̃ = ( (M − min M) / (max M − min M) )^γ ,   γ = 0.6"),
  FIG("gradcam", "gradcam_pipeline.png", "Grad-CAM pipeline for word-level explanations", 3.2),

  H2("5.10", "Visual Question Answering"),
  P("For the Ask feature PixelProse uses **BLIP-VQA** (ViT-B/16 backbone). The image is encoded by the ViT. The question, for example “what is the woman wearing?”, is encoded by a BERT encoder that cross-attends to the image embeddings, producing a question representation grounded in the picture. An answer decoder then generates the answer autoregressively with beam search (3 beams, at most 12 tokens) while cross-attending to the question representation. The answer confidence is exp of the length-normalised beam score. Questions are normalised (whitespace collapsed, a question mark appended, length limited to 200 characters) before encoding."),

  H2("5.11", "Post-processing"),
  P("The raw decoder output is converted into user-facing text by a deterministic post-processing algorithm:"),
  NUM([
    "Remove the conditioning prompt (“a picture of”) if it was not supplied by the user.",
    "Delete known BLIP artefact tokens (“arafed”, “araffe”, …) and a leading filler phrase (“there is”, “there are”, “this is”).",
    "Collapse immediate word repetitions (“the the” → “the”) and patterns such as “lava and lava” → “lava”.",
    "Normalise whitespace and punctuation; discard candidates with fewer than two words.",
    "Produce the display sentence (capitalised, full stop), keywords (content words after stop-word removal), hashtags, an accessible HTML alt-text snippet and the word count.",
  ]),
  P("In parallel, the image analysis module extracts the six dominant colours by median-cut quantisation of a 160-pixel thumbnail, together with the resolution, aspect ratio, orientation, format, file size and the mean brightness of the image, which is classified as bright, balanced or dark."),

  H2("5.12", "Evaluation Metrics"),
  P("To measure caption quality objectively we implemented the three most widely used reference-based metrics, following their original definitions and the MS-COCO evaluation toolkit. Let c be a candidate caption and S = {s₁, …, s_m} its human references."),
  H3("5.12.1", "BLEU"),
  P("BLEU {ref:bleu} computes the *modified n-gram precision* pₙ, the fraction of candidate n-grams that also occur in some reference with counts clipped to the maximum reference count, combines n = 1…4 with a geometric mean and multiplies by a brevity penalty BP that punishes captions shorter than the references (c: candidate length, r: effective reference length, summed over the corpus):"),
  EQ("bleu", "BLEU-N = BP · exp( Σₙ₌₁ᴺ (1/N) log pₙ ) ,   BP = 1 if c > r, else exp(1 − r/c)"),
  H3("5.12.2", "ROUGE-L"),
  P("ROUGE-L {ref:rouge} uses the length of the longest common subsequence (LCS) between candidate and reference, which rewards in-order matches without requiring them to be consecutive. Precision and recall use the best reference, and they are combined into an F-measure with β = 1.2:"),
  EQ("rouge", "R = max_j LCS(c, s_j) / |s_j| ,   P = max_j LCS(c, s_j) / |c| ,   ROUGE-L = (1 + β²) R P / (R + β² P)"),
  H3("5.12.3", "CIDEr-D"),
  P("CIDEr {ref:cider} measures consensus with the references using TF-IDF-weighted n-gram vectors, so that informative words (“giraffe”) count more than frequent ones (“a”, “the”). For n-gram ω_k with count h_k(s) in sentence s and document frequency over the |I| images of the test set, the weight is g_k(s) = h_k(s) · log( |I| / df(ω_k) ). The CIDEr-D variant clips candidate weights and adds a Gaussian length penalty to prevent gaming by repetition or length:"),
  EQ("cider", "CIDEr-Dₙ(c, S) = (10/m) Σⱼ exp( −(l_c − l_sⱼ)² / 2σ² ) · ( min(gⁿ(c), gⁿ(sⱼ)) · gⁿ(sⱼ) ) / ( ‖gⁿ(c)‖ ‖gⁿ(sⱼ)‖ ) ,   σ = 6"),
  EQ("cider2", "CIDEr-D(c, S) = (1/4) Σₙ₌₁⁴ CIDEr-Dₙ(c, S)"),
  P("In addition we report the mean ITM match probability of the chosen captions (a reference-free grounding measure) and the latency per image."),

  H2("5.13", "Overall Algorithm"),
  P("The complete caption-generation procedure, as implemented in app/services/captioner.py, is summarised below."),
  CODE([
    "Algorithm PixelProse-Caption(image I, options opt)",
    "  1  I  ← validate, EXIF-rotate, convert to RGB, downscale(I)",
    "  2  key ← (SHA1(I), normalise(opt));  if opt.strategy = beam and key ∈ Cache: return Cache[key]",
    "  3  x  ← resize(I, 384×384); normalise with CLIP mean/std          ▷ Eq. norm",
    "  4  V  ← ViT(x)                                   ▷ 577 × 1024, computed once",
    "  5  prompt ← opt.prompt or \"a picture of\"",
    "  6  C ← ∅",
    "  7  if strategy ∈ {beam, hybrid}:     C ← C ∪ BeamSearch(V, prompt, k = 5)",
    "  8  if strategy ∈ {hybrid, sampling}: C ← C ∪ NucleusSample(V, prompt, p = 0.9, T)",
    "  9  C ← unique( clean(c) for c in C )",
    " 10  for each c in C:  conf(c) ← exp(mean log P(c | V))      ▷ one batched pass",
    " 11  if opt.rerank:     for each c in C: S(c) ← 0.65·P_itm(I, c) + 0.35·conf(c)",
    " 12  else:              S(c) ← conf(c)",
    " 13  best ← argmax_c S(c)",
    " 14  result ← {best, sorted C, word probabilities, keywords, hashtags, palette, timings}",
    " 15  Cache[key] ← result;  return result",
  ], "Pseudocode of the caption-generation algorithm"),
  P("The time complexity is dominated by the single ViT forward pass, O(L·N²·D) for N = 577 tokens, and by beam decoding, O(k·n) decoder steps each costing O(n·D + N·D) due to self- and cross-attention. Encoding the image once instead of once per candidate, and scoring all candidates in one batched pass, are the two key optimisations of our pipeline."),
];
