const { H1, H2, H3, P, BUL, NUM, FIG, TAB, CODE } = require("../lib");

module.exports = [
  H1(6, "IMPLEMENTATION DETAILS"),

  H2("6.1", "Introduction"),
  P("This chapter describes how the design of Chapter 4 and the methodology of Chapter 5 were implemented. We present the development environment and technology stack, the source-code organisation, the key backend and frontend modules with representative code, screenshots of the working system with a description of each, the testing performed and the deployment procedure. The complete source code is maintained in a Git repository."),

  H2("6.2", "Development Environment and Technology Stack"),
  TAB("stack",
    ["Layer", "Technology", "Role in PixelProse"],
    [
      ["AI framework", "PyTorch 2.x {ref:pytorch}", "Tensor operations, inference, autograd for Grad-CAM"],
      ["Model library", "Hugging Face Transformers 4.5x {ref:hf}", "BlipForConditionalGeneration, BlipForImageTextRetrieval, BlipForQuestionAnswering, processors"],
      ["Models", "Salesforce BLIP {ref:blip}", "Captioning (large, base), ITM, VQA"],
      ["Web API", "FastAPI {ref:fastapi} + Uvicorn", "REST endpoints, validation (Pydantic), OpenAPI documentation"],
      ["Imaging", "Pillow, NumPy", "Decoding, EXIF, resizing, palette extraction, statistics"],
      ["Frontend", "HTML5, CSS3, JavaScript ES modules", "Single-page interface without a build step"],
      ["Browser APIs", "Canvas 2D, Web Speech, MediaDevices, Clipboard, localStorage", "Heatmaps and cards, text-to-speech, webcam, paste, history"],
      ["Testing", "pytest, FastAPI TestClient", "Unit and API tests with mocked models"],
      ["Tooling", "Git/GitHub, VS Code, PlantUML, Matplotlib, Playwright", "Version control, editing, diagrams, charts, UI screenshots"],
    ],
    "Technology stack",
    [1.4, 2.6, 3.8]),

  H2("6.3", "Project Structure"),
  P("The repository separates concerns into clear top-level folders: **app/** contains the FastAPI application (config.py for settings, main.py for routes, schemas.py for request models) and the **services/** package with one module per responsibility (model_manager, captioner, matcher, vqa, image_utils, text_utils, metrics and store). **static/** holds the single-page interface (index.html, one stylesheet and twelve JavaScript modules). **scripts/** contains the model download, offline conversion and evaluation tools, **sample_images/** the 44 test images with their reference captions, **tests/** the pytest suite, and **docs/**, **presentation/** and **report/** the documentation, slide deck and this report, each generated from source. run.py starts the web server and cli.py provides the command-line interface."),

  H2("6.4", "Backend Implementation"),
  H3("6.4.1", "Configuration and Model Management"),
  P("All settings (model sources, device, feature toggles, limits) are read once from environment variables or a .env file into an immutable Settings object, so the same code can run with Hugging Face Hub models or locally converted weights. The **ModelManager** loads each model at most once using double-checked locking, selects CUDA, Apple MPS or CPU automatically, and uses half precision on GPUs. During testing we found that PyTorch's worker threads spin-wait: when the browser's rendering occupied one CPU core, a caption that normally takes about 5 seconds took more than 90 seconds. The manager therefore reserves one core and serialises CPU inference with a shared re-entrant lock:"),
  P("Models are preloaded in a background thread when the server starts, so the web page is usable immediately while a status pill reports progress through /api/health."),

  H3("6.4.2", "Caption Generation"),
  P("The **Captioner** implements the pipeline of Section 5.13. The key optimisation is that the Vision Transformer runs once and every decoding call reuses the image embeddings. It achieves this by calling the text decoder directly with the same preparation that BLIP's generate() performs internally:"),
  CODE([
    "def _encode(self, lm, image, prompt):",
    "    inputs = lm.processor(images=image, text=prompt, return_tensors=\"pt\")",
    "    pixel_values = inputs[\"pixel_values\"].to(device, dtype)",
    "    image_embeds = lm.model.vision_model(pixel_values=pixel_values)[0]   # once per image",
    "    input_ids = inputs[\"input_ids\"].to(device)",
    "    input_ids[:, 0] = lm.model.config.text_config.bos_token_id          # [CLS] -> [DEC]",
    "    return image_embeds, input_ids[:, :-1], inputs[\"attention_mask\"].to(device)[:, :-1]",
  ], "Encoding the image once (captioner.py)"),
  P("Candidates from beam search and sampling are cleaned and de-duplicated, padded into one batch and scored with a single teacher-forced pass that gathers the log-probability of every generated token. The ITM Matcher then scores all candidates in one batch, and the blended score of Eq. {eq:final} selects the caption. Every stage is timed, and the timings are returned for the *Pipeline timing* panel of the interface."),

  H3("6.4.3", "Matching and Grad-CAM Grounding"),
  P("The **Matcher** loads BLIP-ITM with the eager attention implementation so that attention probabilities are materialised and differentiable. Grounding runs a forward pass with output_attentions=True, takes the layer-8 cross-attention and back-propagates the match logit to it with torch.autograd.grad, which computes only the gradient needed without updating any weights:"),
  CODE([
    "with lm.lock, torch.enable_grad():",
    "    out = model.text_encoder(input_ids=ids, attention_mask=mask,",
    "                             encoder_hidden_states=image_embeds,",
    "                             encoder_attention_mask=image_mask, output_attentions=True)",
    "    cross = out.cross_attentions[8]                       # (1, heads, tokens, 1 + 576)",
    "    logit = model.itm_head(out.last_hidden_state[:, 0, :])[:, 1].sum()",
    "    grads = torch.autograd.grad(logit, cross)[0]",
    "cam = (cross.detach() * grads.clamp(min=0)).mean(dim=1)[0, :, 1:]   # Eq. {eq:cam}",
    "cam = _smooth(cam.reshape(-1, 24, 24))                             # Gaussian 5x5",
  ], "Grad-CAM on cross-attention (matcher.py)"),

  H3("6.4.4", "REST API, Validation and Caching"),
  P("FastAPI routes are thin: they resolve the image (file, URL or image_id), build a CaptionOptions object, consult the cache and delegate to the services. Request bodies are validated by Pydantic models with length and range limits. A URL image is downloaded by the server only after its host resolves to a public IP address, and the check is repeated after redirects to prevent server-side request forgery. Custom exception handlers convert image errors to HTTP 400 and model-loading failures to HTTP 503 with guidance for offline setup. JSON responses larger than 1 KB are gzip-compressed. The Swagger UI documentation is served from local files, so it also works without internet."),

  H3("6.4.5", "Offline Model Conversion"),
  P("Some campus networks block huggingface.co. The script convert_original_blip.py downloads Salesforce's original research checkpoints from Google Cloud Storage, renames their parameters to the Transformers layout, interpolates position embeddings where needed (the VQA checkpoint was trained at 480 px) and writes ready-to-use model folders. While developing it we discovered that BlipTextConfig defaults to 8 attention heads whereas BLIP uses 12. Because the weight shapes are identical, the wrong configuration loads without any error, yet the ITM probability of a correct caption dropped from 0.996 to 0.02. Validating against a known reference output exposed this silent bug."),

  H2("6.5", "Frontend Implementation"),
  P("The interface is a single HTML page styled by one CSS file with design tokens (colours, radii, easing curves) defined as custom properties for dark and light themes. Behaviour is split into twelve ES modules, listed in {tab:js}."),
  TAB("js",
    ["Module", "Responsibility"],
    [
      ["main.js", "Bootstraps all modules, theme handling, keyboard shortcuts"],
      ["api.js", "Fetch wrapper with readable error messages and status codes"],
      ["ui.js", "Shared helpers: toasts, tooltips, tabs, sliders, ripples, sparkles, count-ups, storage"],
      ["effects.js", "Scroll reveals, particle network canvas, word rotator, magnetic buttons, tilt, demo card"],
      ["studio.js", "Input sources, settings, generation flow, loading animation, result rendering"],
      ["explain.js", "Heatmap rendering on a canvas overlay, word hover, play mode, opacity"],
      ["chat.js", "Ask (VQA chat) and Match (description scoring) tabs"],
      ["batch.js", "Sequential batch captioning with progress and CSV/JSON export"],
      ["history.js", "localStorage history drawer with restore, export and clear"],
      ["camera.js", "Webcam start, stop, flip and capture"],
      ["card.js", "1080×1350 shareable caption card drawn on a canvas"],
      ["status.js", "Polls /api/health and updates the model status pill"],
    ],
    "Frontend JavaScript modules",
    [1.6, 6.2]),
  P("Heatmaps are rendered efficiently: the 24×24 grid is written into a tiny 24×24 bitmap coloured with a turbo colour map (with transparency increasing for weak values) and then drawn onto a canvas that exactly overlays the displayed image, letting the browser upscale it smoothly with a blur filter. Decorative animations are paused while inference runs and animation loops stop when their elements are off-screen, which keeps CPU free for the model. The interface honours prefers-reduced-motion and provides keyboard shortcuts (Ctrl+Enter generate, R regenerate, C copy, S speak, H history, T theme, ? help, Esc close)."),

  H2("6.6", "System Implementation Screenshots"),
  P("This section presents the working system. All screenshots were captured from the running application."),
  FIG("s_hero", "img:hero.jpg", "Home page (hero section) of PixelProse", 5.0),
  P("{fig:s_hero} shows the landing section. The animated headline rotates through words (“prose”, “stories”, “captions”), a particle network reacts to the mouse, and a demo card on the right loops through real model outputs with a scanning animation and typewriter text. The navigation bar contains a live model-status pill (“Ready · CPU”), the history button and the theme toggle."),
  FIG("s_result", "img:studio_result.jpg", "Caption Studio with a generated caption and ranked candidates", 5.0),
  P("While a caption is being generated, a scanning beam sweeps the image over a 24×24 grid that matches the patch grid of the Vision Transformer, and the result panel shows an animated neural network with a live checklist of the pipeline stages. {fig:s_result} shows the result for a sample image. The caption “A woman sitting on a beach next to a dog.” is revealed word by word in the caption card, with Copy, Speak, Card and Again actions. Three metric cards show the language-model confidence (55 %), the ITM image-match (99 %) and the inference time. The Candidates tab lists all five beam candidates with their source, confidence, match and blended score. Clicking a candidate promotes it to be the caption."),
  FIG("s_explain", "img:explain_dog.jpg", "Explain tab: attention heatmap and word-by-word confidence", 5.0),
  P("{fig:s_explain} shows the Explain tab. Each caption word is a button, and hovering over it overlays that word's Grad-CAM heatmap on the image. The *Whole caption* button shows the combined map, *Play* animates through the content words and a slider sets the opacity. Below, the word-by-word confidence chart shows the probability of every word; words below 25 % (here “sitting” and “next”) are highlighted in orange as points of hesitation."),
  FIG("s_heat", "heat_pair.png", "Word-level heatmaps produced by Grad-CAM", 6.0),
  P("{fig:s_heat} compares two words of the same caption. For “dog” the heat covers the dog's head and body; for “woman” it moves to the woman's face and upper body. This demonstrates that the model grounds each word in the corresponding region of the image."),
  FIG("s_askmatch", "ask_match.png", "Ask tab (visual question answering) and Match tab (scoring user descriptions)", 5.6),
  P("{fig:s_askmatch}(a) shows the question-answering chat. Questions can be typed or chosen from suggestion chips, and each answer shows its confidence and latency: “what is the woman wearing?” → *plaid shirt*, “where was this taken?” → *beach*, “is the dog happy?” → *yes*. {fig:s_askmatch}(b) shows the Match tab, where users type their own descriptions. The AI caption (99.7 %) and “a woman playing with her dog on the beach” (99.3 %) *fit well*. “A dog giving a high five” receives 29.1 %, since it is partly right but misses the woman, while “a man riding a horse in a field” and “a cat sleeping on a sofa” receive 0.0 %."),
  FIG("s_insights", "img:insights.jpg", "Insights tab: keywords, palette, metadata, timing and alt-text", 4.4),
  P("{fig:s_insights} shows the Insights tab with keywords and hashtags, the dominant colour palette (click to copy hex codes), image details, the time taken by each pipeline stage and an accessible HTML alt-text snippet ready to paste into a web page."),
  FIG("s_batch", "img:batch.jpg", "Batch mode with export to CSV and JSON", 5.0),
  P("{fig:s_batch} shows batch mode: several images are dropped at once, captioned one after another with individual scanning animations and a progress bar, and the results can be exported as CSV or JSON."),
  FIG("s_mobile", "img:mobile_hero.jpg", "Responsive layout on a mobile phone", 2.3),
  P("{fig:s_mobile} shows the responsive layout on a phone. A light theme is also available; it follows the operating-system preference by default and is remembered per browser."),
  FIG("s_api", "api_docs.png", "Interactive REST API documentation (Swagger UI)", 5.6),
  P("{fig:s_api} shows the automatically generated, interactive API documentation, where every endpoint can be tried directly from the browser."),
  FIG("s_cli", "cli.png", "Command-line interface output", 6.0),
  P("{fig:s_cli} shows the command-line tool captioning two images and answering two questions about each. It uses the same services as the web application and can export CSV or JSON."),

  H2("6.7", "Testing"),
  P("Testing was carried out at three levels. **Unit tests** check text processing (prompt stripping, artefact removal, repetition collapse, keywords, hashtags), image handling (format validation, transparency flattening, down-scaling, palette, metadata, SSRF blocking of private URLs) and the metric implementations (a perfect caption scores 1.0 on BLEU and ROUGE-L; a wrong caption scores lower on CIDEr-D). **API tests** exercise every endpoint through FastAPI's TestClient with the neural networks replaced by fast fakes, so the suite of 36 tests runs in about 8 seconds. **End-to-end tests** drove the real interface in a headless Chromium browser with Playwright, covering sample selection, generation, every tab, batch mode, theme switching and the phone layout. They also detected and led to the fix of a horizontal-overflow bug on phones. {tab:tests} lists representative test cases."),
  TAB("tests",
    ["ID", "Test case", "Expected result", "Req.", "Status"],
    [
      ["TC-01", "Upload a valid JPEG and generate", "Caption, candidates, scores and palette returned", "FR-1, 3, 4", "Pass"],
      ["TC-02", "Upload a text file renamed as image", "HTTP 400 “not a readable image”", "FR-2", "Pass"],
      ["TC-03", "Upload a 16 MB image", "Rejected with size message", "FR-2", "Pass"],
      ["TC-04", "URL pointing to 127.0.0.1", "Rejected as private host (SSRF)", "FR-1", "Pass"],
      ["TC-05", "Generate twice with beam search", "Second response served from cache", "FR-3", "Pass"],
      ["TC-06", "Guided prefix “a painting of”", "Caption starts with the prefix", "FR-10", "Pass"],
      ["TC-07", "Invalid parameter (99 candidates)", "HTTP 422 validation error", "FR-10", "Pass"],
      ["TC-08", "Explain a caption", "24×24 map per word + overall map", "FR-7", "Pass"],
      ["TC-09", "Ask “how many cats are there?”", "Answer “2”", "FR-8", "Pass"],
      ["TC-10", "Match correct vs wrong description", "Correct ≫ wrong (99.7 % vs 0.0 %)", "FR-9", "Pass"],
      ["TC-11", "VQA with unknown image_id", "HTTP 404 “upload again”", "FR-8", "Pass"],
      ["TC-12", "Batch with 2 images + 1 text file", "2 captions, 1 error entry", "FR-13", "Pass"],
      ["TC-13", "Restore an entry from history", "Result shown; Explain/Ask work again", "FR-14", "Pass"],
      ["TC-14", "Open /docs offline", "Swagger UI loads from local files", "FR-15", "Pass"],
      ["TC-15", "Phone viewport 390 px", "No horizontal scroll; all features usable", "NFR", "Pass"],
      ["TC-16", "Transparent PNG input", "Flattened on white, not black", "FR-2", "Pass"],
    ],
    "Representative test cases",
    [0.7, 2.3, 2.6, 1.1, 0.7]),

  H2("6.8", "Deployment"),
  P("PixelProse is distributed as a Git repository with one-click scripts:"),
  NUM([
    "**Setup (once):** setup.bat on Windows or ./setup.sh on macOS/Linux creates a Python virtual environment, installs the dependencies (the CPU build of PyTorch on Linux machines without an NVIDIA GPU) and pre-downloads all four models (≈ 4 GB).",
    "**Start:** start.bat or ./start.sh launches Uvicorn on http://127.0.0.1:8000 and opens the browser. With --host 0.0.0.0 phones on the same Wi-Fi can connect.",
    "**Offline networks:** if huggingface.co is blocked, scripts/convert_original_blip.py builds the models from Salesforce's original checkpoints, and .env points the application to the local folders.",
    "**Configuration:** .env.example documents every option, such as the default model, device, feature toggles, thread count, host, port and limits.",
  ]),
];
