// IEEE-style references, keyed for {ref:key} citations. Numbered by order of first citation.
module.exports = {
  who: "World Health Organization, “World report on vision,” Geneva, Switzerland, 2019.",
  webaim: "WebAIM, “The WebAIM Million: An annual accessibility analysis of the top 1,000,000 home pages,” Utah State University. [Online]. Available: https://webaim.org/projects/million/",
  kulkarni: "G. Kulkarni, V. Premraj, S. Dhar, S. Li, Y. Choi, A. C. Berg and T. L. Berg, “Baby talk: Understanding and generating simple image descriptions,” in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2011, pp. 1601–1608.",
  hossain: "M. Z. Hossain, F. Sohel, M. F. Shiratuddin and H. Laga, “A comprehensive survey of deep learning for image captioning,” ACM Computing Surveys, vol. 51, no. 6, pp. 1–36, 2019.",
  stefanini: "M. Stefanini, M. Cornia, L. Baraldi, S. Cascianelli, G. Fiameni and R. Cucchiara, “From show to tell: A survey on deep learning-based image captioning,” IEEE Trans. Pattern Analysis and Machine Intelligence, vol. 45, no. 1, pp. 539–559, 2023.",
  vinyals: "O. Vinyals, A. Toshev, S. Bengio and D. Erhan, “Show and tell: A neural image caption generator,” in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2015, pp. 3156–3164.",
  karpathy: "A. Karpathy and L. Fei-Fei, “Deep visual-semantic alignments for generating image descriptions,” in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2015, pp. 3128–3137.",
  xu: "K. Xu, J. Ba, R. Kiros, K. Cho, A. Courville, R. Salakhutdinov, R. Zemel and Y. Bengio, “Show, attend and tell: Neural image caption generation with visual attention,” in Proc. Int. Conf. Machine Learning (ICML), 2015, pp. 2048–2057.",
  lu: "J. Lu, C. Xiong, D. Parikh and R. Socher, “Knowing when to look: Adaptive attention via a visual sentinel for image captioning,” in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2017, pp. 375–383.",
  rennie: "S. J. Rennie, E. Marcheret, Y. Mroueh, J. Ross and V. Goel, “Self-critical sequence training for image captioning,” in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2017, pp. 7008–7024.",
  anderson: "P. Anderson, X. He, C. Buehler, D. Teney, M. Johnson, S. Gould and L. Zhang, “Bottom-up and top-down attention for image captioning and visual question answering,” in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2018, pp. 6077–6086.",
  vaswani: "A. Vaswani, N. Shazeer, N. Parmar, J. Uszkoreit, L. Jones, A. N. Gomez, Ł. Kaiser and I. Polosukhin, “Attention is all you need,” in Advances in Neural Information Processing Systems (NeurIPS), 2017, pp. 5998–6008.",
  cornia: "M. Cornia, M. Stefanini, L. Baraldi and R. Cucchiara, “Meshed-memory transformer for image captioning,” in Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition (CVPR), 2020, pp. 10578–10587.",
  dosovitskiy: "A. Dosovitskiy, L. Beyer, A. Kolesnikov, D. Weissenborn, X. Zhai, T. Unterthiner, M. Dehghani, M. Minderer, G. Heigold, S. Gelly, J. Uszkoreit and N. Houlsby, “An image is worth 16×16 words: Transformers for image recognition at scale,” in Proc. Int. Conf. Learning Representations (ICLR), 2021.",
  oscar: "X. Li, X. Yin, C. Li, P. Zhang, X. Hu, L. Zhang, L. Wang, H. Hu, L. Dong, F. Wei, Y. Choi and J. Gao, “Oscar: Object-semantics aligned pre-training for vision-language tasks,” in Proc. European Conf. Computer Vision (ECCV), 2020, pp. 121–137.",
  clip: "A. Radford, J. W. Kim, C. Hallacy, A. Ramesh, G. Goh, S. Agarwal, G. Sastry, A. Askell, P. Mishkin, J. Clark, G. Krueger and I. Sutskever, “Learning transferable visual models from natural language supervision,” in Proc. Int. Conf. Machine Learning (ICML), 2021, pp. 8748–8763.",
  albef: "J. Li, R. R. Selvaraju, A. D. Gotmare, S. Joty, C. Xiong and S. C. H. Hoi, “Align before fuse: Vision and language representation learning with momentum distillation,” in Advances in Neural Information Processing Systems (NeurIPS), 2021.",
  blip: "J. Li, D. Li, C. Xiong and S. Hoi, “BLIP: Bootstrapping language-image pre-training for unified vision-language understanding and generation,” in Proc. Int. Conf. Machine Learning (ICML), 2022, pp. 12888–12900.",
  git: "J. Wang, Z. Yang, X. Hu, L. Li, K. Lin, Z. Gan, Z. Liu, C. Liu and L. Wang, “GIT: A generative image-to-text transformer for vision and language,” Trans. Machine Learning Research (TMLR), 2022.",
  blip2: "J. Li, D. Li, S. Savarese and S. Hoi, “BLIP-2: Bootstrapping language-image pre-training with frozen image encoders and large language models,” in Proc. Int. Conf. Machine Learning (ICML), 2023, pp. 19730–19742.",
  gradcam: "R. R. Selvaraju, M. Cogswell, A. Das, R. Vedantam, D. Parikh and D. Batra, “Grad-CAM: Visual explanations from deep networks via gradient-based localization,” in Proc. IEEE Int. Conf. Computer Vision (ICCV), 2017, pp. 618–626.",
  vqa: "S. Antol, A. Agrawal, J. Lu, M. Mitchell, D. Batra, C. L. Zitnick and D. Parikh, “VQA: Visual question answering,” in Proc. IEEE Int. Conf. Computer Vision (ICCV), 2015, pp. 2425–2433.",
  bleu: "K. Papineni, S. Roukos, T. Ward and W.-J. Zhu, “BLEU: A method for automatic evaluation of machine translation,” in Proc. 40th Annual Meeting of the Association for Computational Linguistics (ACL), 2002, pp. 311–318.",
  rouge: "C.-Y. Lin, “ROUGE: A package for automatic evaluation of summaries,” in Text Summarization Branches Out (ACL Workshop), 2004, pp. 74–81.",
  cider: "R. Vedantam, C. L. Zitnick and D. Parikh, “CIDEr: Consensus-based image description evaluation,” in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2015, pp. 4566–4575.",
  spice: "P. Anderson, B. Fernando, M. Johnson and S. Gould, “SPICE: Semantic propositional image caption evaluation,” in Proc. European Conf. Computer Vision (ECCV), 2016, pp. 382–398.",
  coco: "T.-Y. Lin, M. Maire, S. Belongie, J. Hays, P. Perona, D. Ramanan, P. Dollár and C. L. Zitnick, “Microsoft COCO: Common objects in context,” in Proc. European Conf. Computer Vision (ECCV), 2014, pp. 740–755.",
  holtzman: "A. Holtzman, J. Buys, L. Du, M. Forbes and Y. Choi, “The curious case of neural text degeneration,” in Proc. Int. Conf. Learning Representations (ICLR), 2020.",
  bert: "J. Devlin, M.-W. Chang, K. Lee and K. Toutanova, “BERT: Pre-training of deep bidirectional transformers for language understanding,” in Proc. NAACL-HLT, 2019, pp. 4171–4186.",
  hf: "T. Wolf et al., “Transformers: State-of-the-art natural language processing,” in Proc. Conf. Empirical Methods in Natural Language Processing: System Demonstrations (EMNLP), 2020, pp. 38–45.",
  pytorch: "A. Paszke et al., “PyTorch: An imperative style, high-performance deep learning library,” in Advances in Neural Information Processing Systems (NeurIPS), 2019, pp. 8024–8035.",
  fastapi: "S. Ramírez, “FastAPI: Modern, fast (high-performance) web framework for building APIs with Python,” 2018. [Online]. Available: https://fastapi.tiangolo.com",
  cocomo: "B. W. Boehm, Software Engineering Economics. Englewood Cliffs, NJ, USA: Prentice-Hall, 1981.",
  wcag: "World Wide Web Consortium (W3C), “Web Content Accessibility Guidelines (WCAG) 2.1,” W3C Recommendation, 2018. [Online]. Available: https://www.w3.org/TR/WCAG21/",
};
