// Project-specific text for the preliminary pages (cover, certificate, abstract, ...).
module.exports = {
  title: "PixelProse: An Explainable AI Image Caption Generator using Vision–Language Transformers",
  shortTitle: "PixelProse: An Explainable AI Image Caption Generator",
  students: [
    { name: "Kartik Verma", roll: "" },
    { name: "Dhir Thakar", roll: "" },
    { name: "Kushal Soni", roll: "" },
  ],
  division: "LY COMPS-B",
  guide: "Prof. Pradnya Bangale",
  hod: "Dr. Sarita Ambadekar",
  principal: "Dr. Vivek Sunnapwar",
  year: "2026-27",
  place: "Sion, Mumbai-400022",

  abstract: [
    "Image captioning, the automatic generation of a natural-language description for an image, lies at the intersection of computer vision and natural language processing and has important applications in accessibility, image search and assistive technology. Although modern vision–language transformers achieve high benchmark scores, practical captioning tools usually return a single unverified sentence, offer no insight into how it was produced, and often depend on paid cloud services.",
    "This project presents PixelProse, an explainable image caption generator built on the BLIP (Bootstrapping Language-Image Pre-training) family of models. A Vision Transformer encodes the image once into 577 patch embeddings, and an image-grounded text decoder generates several candidate captions using beam search and, optionally, nucleus sampling. Each candidate receives a language-model confidence computed from its token probabilities. An independent image–text matching model then verifies and re-ranks the candidates, so the selected caption is both fluent and grounded in the picture. To make the model transparent, Grad-CAM applied to the cross-attention layers produces a heatmap for every word, showing the image region the word relied on. A visual question-answering model lets users ask free-form questions about the image, and a matching tool scores user-written descriptions.",
    "The system is implemented with PyTorch, Hugging Face Transformers and FastAPI, and it is delivered as an animated, responsive and accessible web application with five input methods, batch processing, history, text-to-speech and a documented REST API and command-line interface. It runs entirely on a laptop CPU. On a hand-annotated set of 44 images with 132 reference captions, the default configuration achieves a CIDEr-D of 1.945, a BLEU-4 of 0.408 and a 92 % mean image–text match in about 3.9 seconds per image, while beam search improves CIDEr-D by 7.6 % over a greedy baseline. PixelProse demonstrates that accurate, verifiable and explainable image captioning is achievable privately on commodity hardware.",
  ],
  keywords: "Image captioning, Vision Transformer, BLIP, beam search, image–text matching, Grad-CAM, explainable AI, visual question answering, CIDEr.",

  abbreviations: [
    ["AI", "Artificial Intelligence"],
    ["API", "Application Programming Interface"],
    ["ASGI", "Asynchronous Server Gateway Interface"],
    ["BERT", "Bidirectional Encoder Representations from Transformers"],
    ["BLEU", "Bilingual Evaluation Understudy"],
    ["BLIP", "Bootstrapping Language-Image Pre-training"],
    ["CIDEr", "Consensus-based Image Description Evaluation"],
    ["CLI", "Command-Line Interface"],
    ["CNN", "Convolutional Neural Network"],
    ["COCO", "Common Objects in Context (dataset)"],
    ["CPU", "Central Processing Unit"],
    ["CUDA", "Compute Unified Device Architecture"],
    ["DFD", "Data Flow Diagram"],
    ["GPU", "Graphics Processing Unit"],
    ["Grad-CAM", "Gradient-weighted Class Activation Mapping"],
    ["HTML", "HyperText Markup Language"],
    ["ITC", "Image–Text Contrastive (learning)"],
    ["ITM", "Image–Text Matching"],
    ["JSON", "JavaScript Object Notation"],
    ["LM", "Language Modelling"],
    ["LRU", "Least Recently Used (cache)"],
    ["LSTM", "Long Short-Term Memory"],
    ["MHSA", "Multi-Head Self-Attention"],
    ["MPS", "Metal Performance Shaders (Apple GPU backend)"],
    ["NLP", "Natural Language Processing"],
    ["PPL", "Perplexity"],
    ["REST", "Representational State Transfer"],
    ["RNN", "Recurrent Neural Network"],
    ["ROUGE", "Recall-Oriented Understudy for Gisting Evaluation"],
    ["SHA", "Secure Hash Algorithm"],
    ["SSRF", "Server-Side Request Forgery"],
    ["TF-IDF", "Term Frequency–Inverse Document Frequency"],
    ["UI", "User Interface"],
    ["UML", "Unified Modelling Language"],
    ["URL", "Uniform Resource Locator"],
    ["ViT", "Vision Transformer"],
    ["VLP", "Vision–Language Pre-training"],
    ["VQA", "Visual Question Answering"],
    ["WCAG", "Web Content Accessibility Guidelines"],
  ],
};
