skinparam dpi 220
skinparam defaultFontName "DejaVu Sans"
skinparam defaultFontSize 12
skinparam shadowing false
skinparam roundCorner 8
skinparam ArrowColor #333333
skinparam ArrowThickness 1.2
skinparam BackgroundColor white
skinparam ActorBorderColor #333333
skinparam ActorBackgroundColor #EDE9FE
skinparam UsecaseBorderColor #5B21B6
skinparam UsecaseBackgroundColor #F5F3FF
skinparam ParticipantBorderColor #5B21B6
skinparam ParticipantBackgroundColor #F5F3FF
skinparam SequenceLifeLineBorderColor #888888
skinparam ClassBorderColor #5B21B6
skinparam ClassBackgroundColor #FAFAFF
skinparam ClassHeaderBackgroundColor #EDE9FE
skinparam ComponentBorderColor #5B21B6
skinparam ComponentBackgroundColor #F5F3FF
skinparam NodeBorderColor #0E7490
skinparam NodeBackgroundColor #ECFEFF
skinparam DatabaseBorderColor #0E7490
skinparam DatabaseBackgroundColor #ECFEFF
skinparam ActivityBorderColor #5B21B6
skinparam ActivityBackgroundColor #F5F3FF
skinparam ActivityDiamondBorderColor #5B21B6
skinparam ActivityDiamondBackgroundColor #EDE9FE
skinparam StateBorderColor #5B21B6
skinparam StateBackgroundColor #F5F3FF
skinparam PackageBorderColor #999999
skinparam RectangleBorderColor #5B21B6
skinparam NoteBackgroundColor #FFFBEB
skinparam NoteBorderColor #D97706
